# Generated by Django 5.0.4 on 2024-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('happy', models.IntegerField(default=0)),
                ('sad', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
                ('fear', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('processed_users', models.TextField(default='')),
            ],
        ),
    ]
