# Generated by Django 5.0.4 on 2024-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_emotiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatoruser',
            name='role',
            field=models.CharField(choices=[('M', 'Moderator'), ('A', 'Admin')], default='M', max_length=1),
        ),
    ]
